#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


        // Minimal includes for basic types
        #define _GNU_SOURCE
        #include <sys/types.h>
        #include <unistd.h>
        #include <locale.h>
        #include <stdint.h>
        #include <stdbool.h>
        #include <stdio.h>
        #include <stdlib.h>
        #include <string.h>
        
        // Enum constants
        #define HOLO_STATE_IDLE 0
        #define HOLO_STATE_PLAYING 1
        #define HOLO_STATE_STOPPED 2
        
        #define LOOP_STATE_IDLE 0
        #define LOOP_STATE_RECORDING 1
        #define LOOP_STATE_PLAYING 2
        #define LOOP_STATE_STOPPED 3
        
        #define PLAYBACK_MODE_NORMAL 0
        #define PLAYBACK_MODE_TRIGGER 1
        
        // Memory loop structure (simplified for Python access)
        struct memory_loop {
            float *buffer;
            uint32_t buffer_size;
            uint32_t recorded_frames;
            uint32_t playback_position;
            bool loop_ready;
            bool recording_to_memory;
            bool is_playing;
            bool pending_record;
            bool pending_stop;
            bool pending_start;
            uint32_t sample_rate;
            char loop_filename[512];
            uint8_t midi_note;
            float volume;
            int current_state;  // Use int for inline enum
        };
        
        // Main data structure (simplified for Python access)
        struct data {
            // Global state
            int current_state;  // Use int for inline enum
            bool recording_enabled;
            char *record_filename;
            
            // Audio parameters
            float volume;
            float playback_speed;
            double sample_position;
            
            // Rubberband parameters
            float pitch_shift;
            bool rubberband_enabled;
            
            // Loop management
            struct memory_loop memory_loops[128];
            uint8_t active_loop_count;
            uint8_t currently_recording_note;
            
            // Playback mode
            int current_playback_mode;  // Use int for inline enum
            
            // Sync mode
            bool sync_mode_enabled;
            uint8_t pulse_loop_note;
            uint32_t pulse_loop_duration;
            bool waiting_for_pulse_reset;
            uint32_t longest_loop_duration;
            float sync_cutoff_percentage;
            
            // Additional fields for demo functionality
            float sync_recording_cutoff_percentage;
            uint32_t max_buffer_size;
            float *silence_buffer;
            float *temp_audio_buffer;
        };
        
        // Global instance for demo/testing
        static struct data* global_data = NULL;
        
        struct data* uphonor_init(void) {
            if (global_data != NULL) {
                return global_data;  // Already initialized
            }
            
            global_data = calloc(1, sizeof(struct data));
            if (!global_data) {
                return NULL;
            }
            
            // Initialize basic fields
            global_data->volume = 1.0f;
            global_data->playback_speed = 1.0f;
            global_data->sample_position = 0.0;
            global_data->recording_enabled = false;
            global_data->record_filename = NULL;
            global_data->current_state = HOLO_STATE_IDLE;
            global_data->pitch_shift = 0.0f;
            global_data->rubberband_enabled = true;
            global_data->current_playback_mode = PLAYBACK_MODE_TRIGGER;
            global_data->sync_mode_enabled = false;
            global_data->pulse_loop_note = 255;  // No pulse loop
            global_data->sync_cutoff_percentage = 0.5f;
            global_data->sync_recording_cutoff_percentage = 0.5f;
            
            // Initialize performance buffers
            global_data->max_buffer_size = 2048 * 8;
            global_data->silence_buffer = calloc(global_data->max_buffer_size, sizeof(float));
            global_data->temp_audio_buffer = malloc(global_data->max_buffer_size * sizeof(float));
            
            // Initialize memory loops
            for (int i = 0; i < 128; i++) {
                global_data->memory_loops[i].buffer = NULL;
                global_data->memory_loops[i].buffer_size = 0;
                global_data->memory_loops[i].recorded_frames = 0;
                global_data->memory_loops[i].playback_position = 0;
                global_data->memory_loops[i].loop_ready = false;
                global_data->memory_loops[i].recording_to_memory = false;
                global_data->memory_loops[i].is_playing = false;
                global_data->memory_loops[i].pending_record = false;
                global_data->memory_loops[i].pending_stop = false;
                global_data->memory_loops[i].pending_start = false;
                global_data->memory_loops[i].sample_rate = 48000;
                global_data->memory_loops[i].loop_filename[0] = '\0';
                global_data->memory_loops[i].midi_note = i;
                global_data->memory_loops[i].volume = 1.0f;
                global_data->memory_loops[i].current_state = LOOP_STATE_IDLE;
            }
            
            global_data->active_loop_count = 0;
            global_data->currently_recording_note = 255;  // No recording
            
            return global_data;
        }
        
        void uphonor_cleanup(struct data* data) {
            if (data == NULL) return;
            
            // Clean up memory loops
            for (int i = 0; i < 128; i++) {
                if (data->memory_loops[i].buffer) {
                    free(data->memory_loops[i].buffer);
                    data->memory_loops[i].buffer = NULL;
                }
            }
            
            // Clean up performance buffers
            if (data->silence_buffer) {
                free(data->silence_buffer);
                data->silence_buffer = NULL;
            }
            
            if (data->temp_audio_buffer) {
                free(data->temp_audio_buffer);
                data->temp_audio_buffer = NULL;
            }
            
            if (data->record_filename) {
                free(data->record_filename);
                data->record_filename = NULL;
            }
            
            free(data);
            if (data == global_data) {
                global_data = NULL;
            }
        }
        
        // Simplified stub functions for demo/testing
        void uphonor_start_recording(struct data* data, uint8_t note) {
            if (data && note < 128) {
                data->memory_loops[note].current_state = LOOP_STATE_RECORDING;
                data->currently_recording_note = note;
                printf("Demo: Started recording loop %d\n", note);
            }
        }
        
        void uphonor_stop_recording(struct data* data, uint8_t note) {
            if (data && note < 128) {
                data->memory_loops[note].current_state = LOOP_STATE_IDLE;
                if (data->currently_recording_note == note) {
                    data->currently_recording_note = 255;
                }
                printf("Demo: Stopped recording loop %d\n", note);
            }
        }
        
        void uphonor_start_playback(struct data* data, uint8_t note) {
            if (data && note < 128) {
                data->memory_loops[note].current_state = LOOP_STATE_PLAYING;
                printf("Demo: Started playback loop %d\n", note);
            }
        }
        
        void uphonor_stop_playback(struct data* data, uint8_t note) {
            if (data && note < 128) {
                data->memory_loops[note].current_state = LOOP_STATE_STOPPED;
                printf("Demo: Stopped playback loop %d\n", note);
            }
        }
        
        void uphonor_set_volume(struct data* data, float volume) {
            if (data) {
                data->volume = volume;
                printf("Demo: Set global volume to %.2f\n", volume);
            }
        }
        
        void uphonor_set_loop_volume(struct data* data, uint8_t note, float volume) {
            if (data && note < 128) {
                data->memory_loops[note].volume = volume;
                printf("Demo: Set loop %d volume to %.2f\n", note, volume);
            }
        }
        
        void uphonor_set_pitch_shift(struct data* data, float semitones) {
            if (data) {
                data->pitch_shift = semitones;
                printf("Demo: Set pitch shift to %.2f semitones\n", semitones);
            }
        }
        
        void uphonor_set_playback_speed(struct data* data, float speed) {
            if (data) {
                data->playback_speed = speed;
                printf("Demo: Set playback speed to %.2f\n", speed);
            }
        }
        
        void uphonor_enable_rubberband(struct data* data, bool enable) {
            if (data) {
                data->rubberband_enabled = enable;
                printf("Demo: %s Rubberband processing\n", enable ? "Enabled" : "Disabled");
            }
        }
        
        void uphonor_set_playback_mode(struct data* data, int mode) {
            if (data) {
                data->current_playback_mode = mode;
                printf("Demo: Set playback mode to %s\n", 
                       mode == PLAYBACK_MODE_NORMAL ? "Normal" : "Trigger");
            }
        }
        
        void uphonor_enable_sync_mode(struct data* data, bool enable) {
            if (data) {
                data->sync_mode_enabled = enable;
                printf("Demo: %s sync mode\n", enable ? "Enabled" : "Disabled");
            }
        }
        
        void uphonor_set_pulse_loop(struct data* data, uint8_t note) {
            if (data) {
                data->pulse_loop_note = note;
                printf("Demo: Set pulse loop to note %d\n", note);
            }
        }
        
        // MIDI note on/off handlers
        void uphonor_note_on(struct data* data, uint8_t note, uint8_t velocity) {
            if (data && note < 128) {
                printf("Demo: Note ON - note=%d, velocity=%d\n", note, velocity);
                // In trigger mode, start recording or playback
                if (data->current_playback_mode == PLAYBACK_MODE_TRIGGER) {
                    if (!data->memory_loops[note].loop_ready) {
                        uphonor_start_recording(data, note);
                    } else {
                        uphonor_start_playback(data, note);
                    }
                }
            }
        }
        
        void uphonor_note_off(struct data* data, uint8_t note, uint8_t velocity) {
            if (data && note < 128) {
                printf("Demo: Note OFF - note=%d, velocity=%d\n", note, velocity);
                // In trigger mode, stop recording or playback
                if (data->current_playback_mode == PLAYBACK_MODE_TRIGGER) {
                    if (data->memory_loops[note].current_state == LOOP_STATE_RECORDING) {
                        uphonor_stop_recording(data, note);
                        data->memory_loops[note].loop_ready = true;
                    } else if (data->memory_loops[note].current_state == LOOP_STATE_PLAYING) {
                        uphonor_stop_playback(data, note);
                    }
                }
            }
        }
        

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 3), // struct data *()(void)
/*  1 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION, 42), // void()(struct data *)
/*  3 */ _CFFI_OP(_CFFI_OP_POINTER, 37), // struct data *
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION, 42), // void()(struct data *, _Bool)
/*  6 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/*  7 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 42), // void()(struct data *, float)
/* 10 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 11 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 12 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 13 */ _CFFI_OP(_CFFI_OP_FUNCTION, 42), // void()(struct data *, int)
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 15 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 16 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION, 42), // void()(struct data *, uint8_t)
/* 18 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 19 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 42), // void()(struct data *, uint8_t, float)
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 23 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18),
/* 24 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/* 25 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION, 42), // void()(struct data *, uint8_t, uint8_t)
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 28 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18),
/* 29 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18),
/* 30 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 31 */ _CFFI_OP(_CFFI_OP_POINTER, 32), // char *
/* 32 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 33 */ _CFFI_OP(_CFFI_OP_ARRAY, 32), // char[512]
/* 34 */ (_cffi_opcode_t)(512),
/* 35 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 36 */ _CFFI_OP(_CFFI_OP_POINTER, 11), // float *
/* 37 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // struct data
/* 38 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // struct memory_loop
/* 39 */ _CFFI_OP(_CFFI_OP_ARRAY, 38), // struct memory_loop[128]
/* 40 */ (_cffi_opcode_t)(128),
/* 41 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22), // uint32_t
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static void _cffi_d_uphonor_cleanup(struct data * x0)
{
  uphonor_cleanup(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_cleanup(PyObject *self, PyObject *arg0)
{
  struct data * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_cleanup(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_cleanup _cffi_d_uphonor_cleanup
#endif

static void _cffi_d_uphonor_enable_rubberband(struct data * x0, _Bool x1)
{
  uphonor_enable_rubberband(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_enable_rubberband(PyObject *self, PyObject *args)
{
  struct data * x0;
  _Bool x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_enable_rubberband", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = (_Bool)_cffi_to_c__Bool(arg1);
  if (x1 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_enable_rubberband(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_enable_rubberband _cffi_d_uphonor_enable_rubberband
#endif

static void _cffi_d_uphonor_enable_sync_mode(struct data * x0, _Bool x1)
{
  uphonor_enable_sync_mode(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_enable_sync_mode(PyObject *self, PyObject *args)
{
  struct data * x0;
  _Bool x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_enable_sync_mode", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = (_Bool)_cffi_to_c__Bool(arg1);
  if (x1 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_enable_sync_mode(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_enable_sync_mode _cffi_d_uphonor_enable_sync_mode
#endif

static struct data * _cffi_d_uphonor_init(void)
{
  return uphonor_init();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_init(PyObject *self, PyObject *noarg)
{
  struct data * result;
  PyObject *pyresult;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = uphonor_init(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(3));
  return pyresult;
}
#else
#  define _cffi_f_uphonor_init _cffi_d_uphonor_init
#endif

static void _cffi_d_uphonor_note_off(struct data * x0, uint8_t x1, uint8_t x2)
{
  uphonor_note_off(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_note_off(PyObject *self, PyObject *args)
{
  struct data * x0;
  uint8_t x1;
  uint8_t x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "uphonor_note_off", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint8_t);
  if (x1 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint8_t);
  if (x2 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_note_off(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_note_off _cffi_d_uphonor_note_off
#endif

static void _cffi_d_uphonor_note_on(struct data * x0, uint8_t x1, uint8_t x2)
{
  uphonor_note_on(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_note_on(PyObject *self, PyObject *args)
{
  struct data * x0;
  uint8_t x1;
  uint8_t x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "uphonor_note_on", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint8_t);
  if (x1 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, uint8_t);
  if (x2 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_note_on(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_note_on _cffi_d_uphonor_note_on
#endif

static void _cffi_d_uphonor_set_loop_volume(struct data * x0, uint8_t x1, float x2)
{
  uphonor_set_loop_volume(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_set_loop_volume(PyObject *self, PyObject *args)
{
  struct data * x0;
  uint8_t x1;
  float x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "uphonor_set_loop_volume", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint8_t);
  if (x1 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  x2 = (float)_cffi_to_c_float(arg2);
  if (x2 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_set_loop_volume(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_set_loop_volume _cffi_d_uphonor_set_loop_volume
#endif

static void _cffi_d_uphonor_set_pitch_shift(struct data * x0, float x1)
{
  uphonor_set_pitch_shift(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_set_pitch_shift(PyObject *self, PyObject *args)
{
  struct data * x0;
  float x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_set_pitch_shift", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = (float)_cffi_to_c_float(arg1);
  if (x1 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_set_pitch_shift(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_set_pitch_shift _cffi_d_uphonor_set_pitch_shift
#endif

static void _cffi_d_uphonor_set_playback_mode(struct data * x0, int x1)
{
  uphonor_set_playback_mode(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_set_playback_mode(PyObject *self, PyObject *args)
{
  struct data * x0;
  int x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_set_playback_mode", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_set_playback_mode(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_set_playback_mode _cffi_d_uphonor_set_playback_mode
#endif

static void _cffi_d_uphonor_set_playback_speed(struct data * x0, float x1)
{
  uphonor_set_playback_speed(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_set_playback_speed(PyObject *self, PyObject *args)
{
  struct data * x0;
  float x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_set_playback_speed", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = (float)_cffi_to_c_float(arg1);
  if (x1 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_set_playback_speed(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_set_playback_speed _cffi_d_uphonor_set_playback_speed
#endif

static void _cffi_d_uphonor_set_pulse_loop(struct data * x0, uint8_t x1)
{
  uphonor_set_pulse_loop(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_set_pulse_loop(PyObject *self, PyObject *args)
{
  struct data * x0;
  uint8_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_set_pulse_loop", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint8_t);
  if (x1 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_set_pulse_loop(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_set_pulse_loop _cffi_d_uphonor_set_pulse_loop
#endif

static void _cffi_d_uphonor_set_volume(struct data * x0, float x1)
{
  uphonor_set_volume(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_set_volume(PyObject *self, PyObject *args)
{
  struct data * x0;
  float x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_set_volume", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = (float)_cffi_to_c_float(arg1);
  if (x1 == (float)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_set_volume(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_set_volume _cffi_d_uphonor_set_volume
#endif

static void _cffi_d_uphonor_start_playback(struct data * x0, uint8_t x1)
{
  uphonor_start_playback(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_start_playback(PyObject *self, PyObject *args)
{
  struct data * x0;
  uint8_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_start_playback", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint8_t);
  if (x1 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_start_playback(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_start_playback _cffi_d_uphonor_start_playback
#endif

static void _cffi_d_uphonor_start_recording(struct data * x0, uint8_t x1)
{
  uphonor_start_recording(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_start_recording(PyObject *self, PyObject *args)
{
  struct data * x0;
  uint8_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_start_recording", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint8_t);
  if (x1 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_start_recording(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_start_recording _cffi_d_uphonor_start_recording
#endif

static void _cffi_d_uphonor_stop_playback(struct data * x0, uint8_t x1)
{
  uphonor_stop_playback(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_stop_playback(PyObject *self, PyObject *args)
{
  struct data * x0;
  uint8_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_stop_playback", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint8_t);
  if (x1 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_stop_playback(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_stop_playback _cffi_d_uphonor_stop_playback
#endif

static void _cffi_d_uphonor_stop_recording(struct data * x0, uint8_t x1)
{
  uphonor_stop_recording(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_uphonor_stop_recording(PyObject *self, PyObject *args)
{
  struct data * x0;
  uint8_t x1;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "uphonor_stop_recording", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(3), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (struct data *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(3), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, uint8_t);
  if (x1 == (uint8_t)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { uphonor_stop_recording(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_uphonor_stop_recording _cffi_d_uphonor_stop_recording
#endif

static int _cffi_const_HOLO_STATE_IDLE(unsigned long long *o)
{
  int n = (HOLO_STATE_IDLE) <= 0;
  *o = (unsigned long long)((HOLO_STATE_IDLE) | 0);  /* check that HOLO_STATE_IDLE is an integer */
  if (!_cffi_check_int(*o, n, 0))
    n |= 2;
  return n;
}

static int _cffi_const_HOLO_STATE_PLAYING(unsigned long long *o)
{
  int n = (HOLO_STATE_PLAYING) <= 0;
  *o = (unsigned long long)((HOLO_STATE_PLAYING) | 0);  /* check that HOLO_STATE_PLAYING is an integer */
  if (!_cffi_check_int(*o, n, 1U))
    n |= 2;
  return n;
}

static int _cffi_const_HOLO_STATE_STOPPED(unsigned long long *o)
{
  int n = (HOLO_STATE_STOPPED) <= 0;
  *o = (unsigned long long)((HOLO_STATE_STOPPED) | 0);  /* check that HOLO_STATE_STOPPED is an integer */
  if (!_cffi_check_int(*o, n, 2U))
    n |= 2;
  return n;
}

static int _cffi_const_LOOP_STATE_IDLE(unsigned long long *o)
{
  int n = (LOOP_STATE_IDLE) <= 0;
  *o = (unsigned long long)((LOOP_STATE_IDLE) | 0);  /* check that LOOP_STATE_IDLE is an integer */
  if (!_cffi_check_int(*o, n, 0))
    n |= 2;
  return n;
}

static int _cffi_const_LOOP_STATE_PLAYING(unsigned long long *o)
{
  int n = (LOOP_STATE_PLAYING) <= 0;
  *o = (unsigned long long)((LOOP_STATE_PLAYING) | 0);  /* check that LOOP_STATE_PLAYING is an integer */
  if (!_cffi_check_int(*o, n, 2U))
    n |= 2;
  return n;
}

static int _cffi_const_LOOP_STATE_RECORDING(unsigned long long *o)
{
  int n = (LOOP_STATE_RECORDING) <= 0;
  *o = (unsigned long long)((LOOP_STATE_RECORDING) | 0);  /* check that LOOP_STATE_RECORDING is an integer */
  if (!_cffi_check_int(*o, n, 1U))
    n |= 2;
  return n;
}

static int _cffi_const_LOOP_STATE_STOPPED(unsigned long long *o)
{
  int n = (LOOP_STATE_STOPPED) <= 0;
  *o = (unsigned long long)((LOOP_STATE_STOPPED) | 0);  /* check that LOOP_STATE_STOPPED is an integer */
  if (!_cffi_check_int(*o, n, 3U))
    n |= 2;
  return n;
}

static int _cffi_const_PLAYBACK_MODE_NORMAL(unsigned long long *o)
{
  int n = (PLAYBACK_MODE_NORMAL) <= 0;
  *o = (unsigned long long)((PLAYBACK_MODE_NORMAL) | 0);  /* check that PLAYBACK_MODE_NORMAL is an integer */
  if (!_cffi_check_int(*o, n, 0))
    n |= 2;
  return n;
}

static int _cffi_const_PLAYBACK_MODE_TRIGGER(unsigned long long *o)
{
  int n = (PLAYBACK_MODE_TRIGGER) <= 0;
  *o = (unsigned long long)((PLAYBACK_MODE_TRIGGER) | 0);  /* check that PLAYBACK_MODE_TRIGGER is an integer */
  if (!_cffi_check_int(*o, n, 1U))
    n |= 2;
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_data(struct data *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->current_state) | 0);  /* check that 'struct data.current_state' is an integer */
  (void)((p->recording_enabled) | 0);  /* check that 'struct data.recording_enabled' is an integer */
  { char * *tmp = &p->record_filename; (void)tmp; }
  { float *tmp = &p->volume; (void)tmp; }
  { float *tmp = &p->playback_speed; (void)tmp; }
  { double *tmp = &p->sample_position; (void)tmp; }
  { float *tmp = &p->pitch_shift; (void)tmp; }
  (void)((p->rubberband_enabled) | 0);  /* check that 'struct data.rubberband_enabled' is an integer */
  { struct memory_loop(*tmp)[128] = &p->memory_loops; (void)tmp; }
  (void)((p->active_loop_count) | 0);  /* check that 'struct data.active_loop_count' is an integer */
  (void)((p->currently_recording_note) | 0);  /* check that 'struct data.currently_recording_note' is an integer */
  (void)((p->current_playback_mode) | 0);  /* check that 'struct data.current_playback_mode' is an integer */
  (void)((p->sync_mode_enabled) | 0);  /* check that 'struct data.sync_mode_enabled' is an integer */
  (void)((p->pulse_loop_note) | 0);  /* check that 'struct data.pulse_loop_note' is an integer */
  (void)((p->pulse_loop_duration) | 0);  /* check that 'struct data.pulse_loop_duration' is an integer */
  (void)((p->waiting_for_pulse_reset) | 0);  /* check that 'struct data.waiting_for_pulse_reset' is an integer */
  (void)((p->longest_loop_duration) | 0);  /* check that 'struct data.longest_loop_duration' is an integer */
  { float *tmp = &p->sync_cutoff_percentage; (void)tmp; }
  { float *tmp = &p->sync_recording_cutoff_percentage; (void)tmp; }
  (void)((p->max_buffer_size) | 0);  /* check that 'struct data.max_buffer_size' is an integer */
  { float * *tmp = &p->silence_buffer; (void)tmp; }
  { float * *tmp = &p->temp_audio_buffer; (void)tmp; }
}
struct _cffi_align_struct_data { char x; struct data y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_memory_loop(struct memory_loop *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { float * *tmp = &p->buffer; (void)tmp; }
  (void)((p->buffer_size) | 0);  /* check that 'struct memory_loop.buffer_size' is an integer */
  (void)((p->recorded_frames) | 0);  /* check that 'struct memory_loop.recorded_frames' is an integer */
  (void)((p->playback_position) | 0);  /* check that 'struct memory_loop.playback_position' is an integer */
  (void)((p->loop_ready) | 0);  /* check that 'struct memory_loop.loop_ready' is an integer */
  (void)((p->recording_to_memory) | 0);  /* check that 'struct memory_loop.recording_to_memory' is an integer */
  (void)((p->is_playing) | 0);  /* check that 'struct memory_loop.is_playing' is an integer */
  (void)((p->pending_record) | 0);  /* check that 'struct memory_loop.pending_record' is an integer */
  (void)((p->pending_stop) | 0);  /* check that 'struct memory_loop.pending_stop' is an integer */
  (void)((p->pending_start) | 0);  /* check that 'struct memory_loop.pending_start' is an integer */
  (void)((p->sample_rate) | 0);  /* check that 'struct memory_loop.sample_rate' is an integer */
  { char(*tmp)[512] = &p->loop_filename; (void)tmp; }
  (void)((p->midi_note) | 0);  /* check that 'struct memory_loop.midi_note' is an integer */
  { float *tmp = &p->volume; (void)tmp; }
  (void)((p->current_state) | 0);  /* check that 'struct memory_loop.current_state' is an integer */
}
struct _cffi_align_struct_memory_loop { char x; struct memory_loop y; };

static const struct _cffi_global_s _cffi_globals[] = {
  { "HOLO_STATE_IDLE", (void *)_cffi_const_HOLO_STATE_IDLE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "HOLO_STATE_PLAYING", (void *)_cffi_const_HOLO_STATE_PLAYING, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "HOLO_STATE_STOPPED", (void *)_cffi_const_HOLO_STATE_STOPPED, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "LOOP_STATE_IDLE", (void *)_cffi_const_LOOP_STATE_IDLE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "LOOP_STATE_PLAYING", (void *)_cffi_const_LOOP_STATE_PLAYING, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "LOOP_STATE_RECORDING", (void *)_cffi_const_LOOP_STATE_RECORDING, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "LOOP_STATE_STOPPED", (void *)_cffi_const_LOOP_STATE_STOPPED, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "PLAYBACK_MODE_NORMAL", (void *)_cffi_const_PLAYBACK_MODE_NORMAL, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "PLAYBACK_MODE_TRIGGER", (void *)_cffi_const_PLAYBACK_MODE_TRIGGER, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "uphonor_cleanup", (void *)_cffi_f_uphonor_cleanup, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 2), (void *)_cffi_d_uphonor_cleanup },
  { "uphonor_enable_rubberband", (void *)_cffi_f_uphonor_enable_rubberband, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 5), (void *)_cffi_d_uphonor_enable_rubberband },
  { "uphonor_enable_sync_mode", (void *)_cffi_f_uphonor_enable_sync_mode, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 5), (void *)_cffi_d_uphonor_enable_sync_mode },
  { "uphonor_init", (void *)_cffi_f_uphonor_init, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 0), (void *)_cffi_d_uphonor_init },
  { "uphonor_note_off", (void *)_cffi_f_uphonor_note_off, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 26), (void *)_cffi_d_uphonor_note_off },
  { "uphonor_note_on", (void *)_cffi_f_uphonor_note_on, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 26), (void *)_cffi_d_uphonor_note_on },
  { "uphonor_set_loop_volume", (void *)_cffi_f_uphonor_set_loop_volume, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 21), (void *)_cffi_d_uphonor_set_loop_volume },
  { "uphonor_set_pitch_shift", (void *)_cffi_f_uphonor_set_pitch_shift, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 9), (void *)_cffi_d_uphonor_set_pitch_shift },
  { "uphonor_set_playback_mode", (void *)_cffi_f_uphonor_set_playback_mode, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 13), (void *)_cffi_d_uphonor_set_playback_mode },
  { "uphonor_set_playback_speed", (void *)_cffi_f_uphonor_set_playback_speed, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 9), (void *)_cffi_d_uphonor_set_playback_speed },
  { "uphonor_set_pulse_loop", (void *)_cffi_f_uphonor_set_pulse_loop, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 17), (void *)_cffi_d_uphonor_set_pulse_loop },
  { "uphonor_set_volume", (void *)_cffi_f_uphonor_set_volume, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 9), (void *)_cffi_d_uphonor_set_volume },
  { "uphonor_start_playback", (void *)_cffi_f_uphonor_start_playback, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 17), (void *)_cffi_d_uphonor_start_playback },
  { "uphonor_start_recording", (void *)_cffi_f_uphonor_start_recording, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 17), (void *)_cffi_d_uphonor_start_recording },
  { "uphonor_stop_playback", (void *)_cffi_f_uphonor_stop_playback, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 17), (void *)_cffi_d_uphonor_stop_playback },
  { "uphonor_stop_recording", (void *)_cffi_f_uphonor_stop_recording, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 17), (void *)_cffi_d_uphonor_stop_recording },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "current_state", offsetof(struct data, current_state),
                     sizeof(((struct data *)0)->current_state),
                     _CFFI_OP(_CFFI_OP_NOOP, 15) },
  { "recording_enabled", offsetof(struct data, recording_enabled),
                         sizeof(((struct data *)0)->recording_enabled),
                         _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "record_filename", offsetof(struct data, record_filename),
                       sizeof(((struct data *)0)->record_filename),
                       _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "volume", offsetof(struct data, volume),
              sizeof(((struct data *)0)->volume),
              _CFFI_OP(_CFFI_OP_NOOP, 11) },
  { "playback_speed", offsetof(struct data, playback_speed),
                      sizeof(((struct data *)0)->playback_speed),
                      _CFFI_OP(_CFFI_OP_NOOP, 11) },
  { "sample_position", offsetof(struct data, sample_position),
                       sizeof(((struct data *)0)->sample_position),
                       _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "pitch_shift", offsetof(struct data, pitch_shift),
                   sizeof(((struct data *)0)->pitch_shift),
                   _CFFI_OP(_CFFI_OP_NOOP, 11) },
  { "rubberband_enabled", offsetof(struct data, rubberband_enabled),
                          sizeof(((struct data *)0)->rubberband_enabled),
                          _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "memory_loops", offsetof(struct data, memory_loops),
                    sizeof(((struct data *)0)->memory_loops),
                    _CFFI_OP(_CFFI_OP_NOOP, 39) },
  { "active_loop_count", offsetof(struct data, active_loop_count),
                         sizeof(((struct data *)0)->active_loop_count),
                         _CFFI_OP(_CFFI_OP_NOOP, 19) },
  { "currently_recording_note", offsetof(struct data, currently_recording_note),
                                sizeof(((struct data *)0)->currently_recording_note),
                                _CFFI_OP(_CFFI_OP_NOOP, 19) },
  { "current_playback_mode", offsetof(struct data, current_playback_mode),
                             sizeof(((struct data *)0)->current_playback_mode),
                             _CFFI_OP(_CFFI_OP_NOOP, 15) },
  { "sync_mode_enabled", offsetof(struct data, sync_mode_enabled),
                         sizeof(((struct data *)0)->sync_mode_enabled),
                         _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "pulse_loop_note", offsetof(struct data, pulse_loop_note),
                       sizeof(((struct data *)0)->pulse_loop_note),
                       _CFFI_OP(_CFFI_OP_NOOP, 19) },
  { "pulse_loop_duration", offsetof(struct data, pulse_loop_duration),
                           sizeof(((struct data *)0)->pulse_loop_duration),
                           _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "waiting_for_pulse_reset", offsetof(struct data, waiting_for_pulse_reset),
                               sizeof(((struct data *)0)->waiting_for_pulse_reset),
                               _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "longest_loop_duration", offsetof(struct data, longest_loop_duration),
                             sizeof(((struct data *)0)->longest_loop_duration),
                             _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "sync_cutoff_percentage", offsetof(struct data, sync_cutoff_percentage),
                              sizeof(((struct data *)0)->sync_cutoff_percentage),
                              _CFFI_OP(_CFFI_OP_NOOP, 11) },
  { "sync_recording_cutoff_percentage", offsetof(struct data, sync_recording_cutoff_percentage),
                                        sizeof(((struct data *)0)->sync_recording_cutoff_percentage),
                                        _CFFI_OP(_CFFI_OP_NOOP, 11) },
  { "max_buffer_size", offsetof(struct data, max_buffer_size),
                       sizeof(((struct data *)0)->max_buffer_size),
                       _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "silence_buffer", offsetof(struct data, silence_buffer),
                      sizeof(((struct data *)0)->silence_buffer),
                      _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "temp_audio_buffer", offsetof(struct data, temp_audio_buffer),
                         sizeof(((struct data *)0)->temp_audio_buffer),
                         _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "buffer", offsetof(struct memory_loop, buffer),
              sizeof(((struct memory_loop *)0)->buffer),
              _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "buffer_size", offsetof(struct memory_loop, buffer_size),
                   sizeof(((struct memory_loop *)0)->buffer_size),
                   _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "recorded_frames", offsetof(struct memory_loop, recorded_frames),
                       sizeof(((struct memory_loop *)0)->recorded_frames),
                       _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "playback_position", offsetof(struct memory_loop, playback_position),
                         sizeof(((struct memory_loop *)0)->playback_position),
                         _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "loop_ready", offsetof(struct memory_loop, loop_ready),
                  sizeof(((struct memory_loop *)0)->loop_ready),
                  _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "recording_to_memory", offsetof(struct memory_loop, recording_to_memory),
                           sizeof(((struct memory_loop *)0)->recording_to_memory),
                           _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "is_playing", offsetof(struct memory_loop, is_playing),
                  sizeof(((struct memory_loop *)0)->is_playing),
                  _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "pending_record", offsetof(struct memory_loop, pending_record),
                      sizeof(((struct memory_loop *)0)->pending_record),
                      _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "pending_stop", offsetof(struct memory_loop, pending_stop),
                    sizeof(((struct memory_loop *)0)->pending_stop),
                    _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "pending_start", offsetof(struct memory_loop, pending_start),
                     sizeof(((struct memory_loop *)0)->pending_start),
                     _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "sample_rate", offsetof(struct memory_loop, sample_rate),
                   sizeof(((struct memory_loop *)0)->sample_rate),
                   _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "loop_filename", offsetof(struct memory_loop, loop_filename),
                     sizeof(((struct memory_loop *)0)->loop_filename),
                     _CFFI_OP(_CFFI_OP_NOOP, 33) },
  { "midi_note", offsetof(struct memory_loop, midi_note),
                 sizeof(((struct memory_loop *)0)->midi_note),
                 _CFFI_OP(_CFFI_OP_NOOP, 19) },
  { "volume", offsetof(struct memory_loop, volume),
              sizeof(((struct memory_loop *)0)->volume),
              _CFFI_OP(_CFFI_OP_NOOP, 11) },
  { "current_state", offsetof(struct memory_loop, current_state),
                     sizeof(((struct memory_loop *)0)->current_state),
                     _CFFI_OP(_CFFI_OP_NOOP, 15) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "data", 37, _CFFI_F_CHECK_FIELDS,
    sizeof(struct data), offsetof(struct _cffi_align_struct_data, y), 0, 22 },
  { "memory_loop", 38, _CFFI_F_CHECK_FIELDS,
    sizeof(struct memory_loop), offsetof(struct _cffi_align_struct_memory_loop, y), 22, 15 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  NULL,  /* no enums */
  NULL,  /* no typenames */
  25,  /* num_globals */
  2,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  43,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__uphonor_cffi(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__uphonor_cffi(void) { return NULL; }
#  else
     init_uphonor_cffi(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__uphonor_cffi(void)
{
  return _cffi_init("_uphonor_cffi", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_uphonor_cffi(void)
{
  _cffi_init("_uphonor_cffi", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
